// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package sqlc

import (
	"context"
)

const createArtist = `-- name: CreateArtist :exec
INSERT INTO artists (Name)
VALUES ($1)
`

func (q *Queries) CreateArtist(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, createArtist, name)
	return err
}

const createSongToArtist = `-- name: CreateSongToArtist :exec
INSERT INTO artistsToSongs (ArtistID, SongID)
VALUES ($1, $2)
`

type CreateSongToArtistParams struct {
	Artistid int32 `db:"artistid" json:"Artistid"`
	Songid   int64 `db:"songid" json:"Songid"`
}

func (q *Queries) CreateSongToArtist(ctx context.Context, arg CreateSongToArtistParams) error {
	_, err := q.db.Exec(ctx, createSongToArtist, arg.Artistid, arg.Songid)
	return err
}
