// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	Artistid int32  `db:"artistid" json:"Artistid"`
	Name     string `db:"name" json:"Name"`
}

type Artiststosong struct {
	Artistid int32 `db:"artistid" json:"Artistid"`
	Songid   int64 `db:"songid" json:"Songid"`
}

type Song struct {
	Songid      int64       `db:"songid" json:"Songid"`
	Language    string      `db:"language" json:"Language"`
	Title       string      `db:"title" json:"Title"`
	Isgenerated pgtype.Bool `db:"isgenerated" json:"Isgenerated"`
	Lyrics      pgtype.Text `db:"lyrics" json:"Lyrics"`
}

type User struct {
	Userid        int64       `db:"userid" json:"Userid"`
	Username      string      `db:"username" json:"Username"`
	Password      string      `db:"password" json:"Password"`
	Generatecount pgtype.Int4 `db:"generatecount" json:"Generatecount"`
}

type Userstosong struct {
	Songid int64 `db:"songid" json:"Songid"`
	Userid int32 `db:"userid" json:"Userid"`
}
