// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (Username, Password)
VALUES ($1, $2)
`

type CreateUserParams struct {
	Username string `db:"username" json:"Username"`
	Password string `db:"password" json:"Password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Password)
	return err
}

const createUserToSong = `-- name: CreateUserToSong :exec
INSERT INTO usersToSongs (SongID, UserID)
VALUES ($1, $2)
`

type CreateUserToSongParams struct {
	Songid int64 `db:"songid" json:"Songid"`
	Userid int32 `db:"userid" json:"Userid"`
}

func (q *Queries) CreateUserToSong(ctx context.Context, arg CreateUserToSongParams) error {
	_, err := q.db.Exec(ctx, createUserToSong, arg.Songid, arg.Userid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT userid, username, password, generatecount FROM users
WHERE users.Username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Password,
		&i.Generatecount,
	)
	return i, err
}

const incrementUserCount = `-- name: IncrementUserCount :exec
UPDATE users
SET GenerateCount = GenerateCount + 1
WHERE users.UserID = $1
`

func (q *Queries) IncrementUserCount(ctx context.Context, userid int64) error {
	_, err := q.db.Exec(ctx, incrementUserCount, userid)
	return err
}
