-- Migration: 0001_init.sql
-- Description: Initial Schema For KaraokeAssistant
-- Author: Bob Lin
-- Created: 2026

CREATE TABLE IF NOT EXISTS artists (
	ArtistID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS songs (
	SongID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Language VARCHAR(3) DEFAULT 'eng' NOT NULL,
	Title VARCHAR(512) NOT NULL,
	IsGenerated BOOLEAN DEFAULT True,
	Lyrics TEXT
);

CREATE INDEX idx_song_name ON songs (Title);

CREATE TABLE IF NOT EXISTS artistsToSongs (
	ArtistID INT REFERENCES artists (ArtistID),
	SongID BIGINT REFERENCES songs (SongID),
	PRIMARY KEY (ArtistID, SongID)
);

CREATE TABLE IF NOT EXISTS users (
	UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Username VARCHAR(64) CHECK (Username > 3) UNIQUE NOT NULL,
	Password VARCHAR(128) CHECK (Password > 8) NOT NULL,
	GenerateCount INT DEFAULT 0
);

CREATE INDEX idx_user_username ON users (Username);
CREATE INDEX idx_user_userid ON users (UserID);
	
CREATE TABLE IF NOT EXISTS usersToSongs (
	SongID BIGINT REFERENCES songs (SongID),
	UserID INT REFERENCES users (UserID),
	PRIMARY KEY (UserID, SongID)
);

-- Haven't Found A Use For Triggers And Functions Yet
