// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package sqlc

import (
	"context"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (Name)
VALUES ($1)
RETURNING artistid, name
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.Artistid, &i.Name)
	return i, err
}

const createSongToArtist = `-- name: CreateSongToArtist :one
INSERT INTO artistsToSongs (ArtistID, SongID)
VALUES ($1, $2)
RETURNING artistid, songid
`

type CreateSongToArtistParams struct {
	Artistid int32 `db:"artistid" json:"Artistid"`
	Songid   int64 `db:"songid" json:"Songid"`
}

func (q *Queries) CreateSongToArtist(ctx context.Context, arg CreateSongToArtistParams) (Artiststosong, error) {
	row := q.db.QueryRow(ctx, createSongToArtist, arg.Artistid, arg.Songid)
	var i Artiststosong
	err := row.Scan(&i.Artistid, &i.Songid)
	return i, err
}
